#'@title Get Current Top Media By Location ID
#'
#'@description Gets the top 9 media posts for a location with the given location ID.
#'
#'@param mapping A location mapping in the form generated by createLocationMapping
#'@param r       Radius of search from give coordinates
#'@param lat     Double for latitude of search center
#'@param long    Double for longitude of search center
#'@param ...    Additional options passed to a shinyAppDir
#'@import dplyr
#'
#'@return n x 9 DF where n is the number of locations in the scope: \cr
#'id, name, slug, city_ID, city_Name, city_slug,country_ID, country_Name, country_Slug
#'
#'
#'@examples
#'\dontrun{
#'mapping <- createLocationMapping("United States", "New York", TRUE)
#'
#'lat <- 40.7484
#'long <- 73.9857
#'radius <- 0.5 #miles
#'
#'smaller_mapping <- getLocationsInRange(mapping, radius, lat, long)}
#'@export

# Get Locations In Range
#
# returns the locations in Location Mapping
#
#INPUTS:
#mapping - A location mapping in the form generated by createLocationMapping
#r -       Radius of search from give coordinates
#lat -     Double for latitude of search center
#long -    Double for longitude of search center
#
#OUTPUTS:
#
# n x 9 DF where n is the number of locations in the scope:
# id, name, slug, city_ID, city_Name, city_slug,country_ID, country_Name, country_Slug

getLocationsInRange <- function(mapping, r, lat, long, ...){

  if(!is.numeric(r) || !is.numeric(lat) || !is.numeric(long)){
    stop("r, lat, and long, must be numeric")
  }

  #stop the binding note
  latitude <- dplyr::quo(latitude)
  longitude <- dplyr::quo(longitude)

  mapping <- filter(mapping, haversineDistance(latitude, longitude, lat, long) <= r)

  return(mapping)
}
